*** Variables ***
&{cart_page_locator}
...    btn_add_item_quantity=id=buttonAddMoreQuantity
...    btn_checkout=id=buttonCheckout
...    btn_confirm_delete=id=com.shopee.th:id/buttonDefaultPositive
...    btn_remove_item_quantity=id=buttonReduceQuantity
...    check_box=xpath=(//android.view.ViewGroup[@resource-id="buttonCheckBoxNotChecked"])[1]/android.view.ViewGroup
...    cart_empty_icon=xpath=//android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[1]/android.widget.ImageView
...    txt_title=id=labelActionBarTitle