*** Variables ***
&{product_page_locator}
...    btn_add_to_cart=id=buttonProductAddCart
...    btn_buy_now=id=miniFeedV2_buy_now_button
...    btn_add_to_cart_modal=class=android.widget.Button
...    btn_cart=xpath=(//android.view.ViewGroup[@resource-id="buttonActionBarView"])[2]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup
...    container_page=id=android:id/content
...    txt_product_name=xpath=//android.widget.TextView[@resource-id="labelProductPageProductName"]