*** Variables ***
&{search_page_locator}
...    btn_search=xpathh=//com.shopee.leego.renderv3.vaf.virtualview.view.nlayout.gxcontainer.drawerlayout.HVDrawerLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[3]
...    product_container=xapth=(//android.widget.FrameLayout[@resource-id="com.shopee.th:id/DRE_VIEW_CONTAINER_ID"])[5]
...    txt_search=class=android.widget.EditText