pipeline {
    agent any
    triggers {
        cron('H 0 * * *') 
    }
    parameters {
        string(name: 'INCLUDE_TAG', defaultValue: '', description: 'Specify tag to run (leave empty for all)')
    }
    stages {
        stage('Install dependencies') {
            steps {
                script {
                    echo '================================= Set Environment =========================================='
                    echo 'Setting up Virtual Environment'
                    bat 'if not exist "venv" (python -m venv venv)'
                    bat 'venv\\Scripts\\python -m pip install --upgrade pip'
                    bat 'venv\\Scripts\\pip install -r requirements.txt' 
                }
            }
        }
        stage('Execute Robot Test') {
            steps {
                script {
                    echo '================================= Test =========================================='
                    def tagCommand = params.INCLUDE_TAG ? "-i ${params.INCLUDE_TAG}" : ""
                    catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                        bat """
                            call venv\\Scripts\\activate
                            robot -d reports\\results ${tagCommand} .
                        """
                    }
                }
            }
        }
    }
    post {
        always {
            echo '================================= Results =========================================='
            echo 'Publishing Robot Results...'
            step([
                $class: 'RobotPublisher',
                outputPath: 'reports/results', 
                outputFileName: 'output.xml',
                reportFileName: 'report.html',
                logFileName: 'log.html',
                disableArchiveOutput: false,
                passThreshold: 100,
                unstableThreshold: 80,
                otherFiles: '*.png'
            ])
        }
        failure {
            echo 'JOB FAILED!'
        }
        success {
            echo 'JOB SUCCESS!'
        }
    }
}