*** Variables ***
&{profile_page_locator}
...    btn_navbar=xpath=//android.widget.TextView[@resource-id="com.shopee.th:id/title" and @text="**replace**"]/parent::android.widget.FrameLayout
...    btn_login=xpath=//android.view.ViewGroup[@resource-id="dreMePageHeader"]/android.view.ViewGroup/android.view.ViewGroup[3]/android.view.ViewGroup[2]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]