*** Variables ***
&{search_page_locator}
...    btn_search=xpath=//com.shopee.leego.renderv3.vaf.virtualview.view.nlayout.gxcontainer.drawerlayout.HVDrawerLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[3]/android.widget.ImageView
...    container_page=id=com.shopee.th:id/swipe_refresh_layout
...    product_container=xapth=//android.widget.TextView[@text="**replace**"]
...    txt_search=class=android.widget.EditText
...    btn_shopee_mall=xpath=//android.widget.TextView[@text="Shopee Mall"]