*** Variables ***
&{search_page_locator}
...    btn_search=id=inputSearchBar
...    btn_shopee_mall=xpath=//android.widget.TextView[@text="Shopee Mall"]
...    ctn_page=id=com.shopee.th:id/swipe_refresh_layout
...    ctn_fiter_lts=xpath=(//android.widget.FrameLayout[@resource-id="com.shopee.th:id/DRE_VIEW_CONTAINER_ID"])/descendant::android.widget.TextView[@text="Shopee Mall"]
...    product_container=xapth=//android.widget.TextView[@text="**replace**"]
...    txt_search=class=android.widget.EditText
